/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest */

#ifndef _Included_JniTest
#define _Included_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniTest
 * Method:    native_helloworld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniTest_native_1helloworld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
