/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mk_test_App */

#ifndef _Included_com_mk_test_App
#define _Included_com_mk_test_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mk_test_App
 * Method:    print_cpp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mk_test_App_print_1cpp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
